-- AUTOGENERATED HYPRLAND CONFIG, converted from hyprland.conf to hyprland.lua
-- ###############################################################################
--
-- You can split this configuration into multiple files with require():
--   require("myColors")  -- looks for myColors.lua next to this file
--
-- Notes on this conversion:
--   * A few dispatchers below (mouse move/resize binds, master-layout dispatchers
--     like orientationnext/swapwithmaster) don't have a fully published Lua
--     signature as of this writing. They're marked with -- VERIFY comments.
--     Use `hyprctl` / the Lua LSP stubs to confirm the exact field names before
--     you trust them blind.

----------------
---- MONITORS ---
----------------

-- See https://wiki.hypr.land/Configuring/Monitors/
hl.monitor({ output = "DP-2",    mode = "1920x1080@144", position = "0x0",    scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60", position = "1920x0", scale = 1 })

hl.workspace_rule({ workspace = 1, monitor = "DP-2" })
hl.workspace_rule({ workspace = 2, monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = 3, monitor = "DP-2" })
hl.workspace_rule({ workspace = 4, monitor = "HDMI-A-1" })

------------------
---- MY PROGRAMS --
------------------

-- Plain Lua locals replace the old $variables
local terminal    = "kitty"
local fileManager  = "dolphin"
local menu         = "noctalia msg panel-toggle launcher"
local browser      = "librewolf"

-----------------
---- AUTOSTART ---
-----------------

-- exec-once -> run once, at compositor start
hl.on("hyprland.start", function()
  hl.dsp.exec_cmd("noctalia")
  hl.dsp.exec_cmd("hyprctl setcursor breeze_cursors 24")
  hl.dsp.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'breeze_cursors'")
  hl.dsp.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 24")
end)

---------------------------------
---- ENVIRONMENT VARIABLES -------
---------------------------------

hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "breeze_cursors")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")

hl.env("XDG_DATA_DIRS", "/run/current-system/sw/share:/home/lamo/.nix-profile/share:/usr/local/share:/usr/share")
hl.env("XDG_CONFIG_HOME", os.getenv("HOME") .. "/.config")
hl.env("XDG_CACHE_HOME", os.getenv("HOME") .. "/.cache")
hl.env("XDG_DATA_HOME", os.getenv("HOME") .. "/.local/share")
hl.env("XDG_STATE_HOME", os.getenv("HOME") .. "/.local/state")
hl.env("XDG_CONFIG_DIRS", "/etc/xdg")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-------------------
---- PERMISSIONS ---
-------------------

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Permission changes require a Hyprland restart, not applied on-the-fly.

-- hl.config({ ecosystem = { enforce_permissions = 1 } })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

---------------------
---- LOOK AND FEEL ---
---------------------

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,

    border_size = 2,

    ["col.active_border"]   = "rgba(33ccffee) rgba(00ff99ee) 45deg",
    ["col.inactive_border"] = "rgba(595959aa)",

    resize_on_border = true,

    -- Please see https://wiki.hypr.land/Configuring/Tearing/ before turning this on
    allow_tearing = false,

    layout = "master",
  },

  decoration = {
    rounding = 3,
    rounding_power = 2,

    active_opacity = 1.0,
    inactive_opacity = 1.0,

    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
      color = "rgba(1a1a1aee)",
    },

    blur = {
      enabled = true,
      size = 3,
      passes = 1,
      vibrancy = 0.1696,
    },
  },

  animations = {
    enabled = true,
  },

  master = {
    new_status = "slave",
    mfact = 0.5,
    smart_resizing = true,
    always_keep_position = false,
  },

  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
  },

  input = {
    kb_layout  = "de",
    kb_variant = "",
    kb_model   = "",
    kb_options = "caps:escape",
    kb_rules   = "",

    follow_mouse = 1,

    sensitivity = -0.3, -- -1.0 - 1.0, 0 means no modification

    touchpad = {
      natural_scroll = false,
    },
  },
})

-- Bezier curves, see https://wiki.hypr.land/Configuring/Animations/#curves
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Animation leaves, see https://wiki.hypr.land/Configuring/Animations/
hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })

-- Gestures, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

--------------------
---- KEYBINDINGS -----
--------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + Return",    hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + D",         hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + B",         hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + V",         hl.dsp.window.float({ action = "toggle" }))
-- VERIFY: classic "fullscreen, 1" is the maximize-style fullscreen (internal only).
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen_state({ internal = 1, client = 0, action = "toggle" }))

-- Move focus with mainMod + hjkl
-- VERIFY: directional window focus signature (hl.dsp.focus vs hl.dsp.window.focus).
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "d" }))

-- Switch workspaces with mainMod + [1-4]
-- Move active window to a workspace with mainMod + SHIFT + [1-4]
for i = 1, 4 do
  hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end

-- VERIFY: relative-workspace movetoworkspace equivalent
hl.bind(mainMod .. " + less",         hl.dsp.window.move({ workspace = "-1" }))
hl.bind(mainMod .. " + SHIFT + less", hl.dsp.window.move({ workspace = "+1" }))

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Resize with keys (repeating)
-- VERIFY: exact field names for directional resize deltas
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.resize({ x = -50, y = 0 }),  { repeating = true })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.resize({ x = 50,  y = 0 }),  { repeating = true })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.resize({ x = 0,   y = 50 }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.resize({ x = 0,   y = -50 }),{ repeating = true })

-- Move/resize windows with mainMod + LMB/RMB and dragging
-- VERIFY: mouse-drag dispatcher names aren't confirmed in public docs yet
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.move_mouse and hl.dsp.window.move_mouse() or hl.dsp.exec_cmd("true"))
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize_mouse and hl.dsp.window.resize_mouse() or hl.dsp.exec_cmd("true"))

-- Master layout dispatchers
-- VERIFY: these were classic `layoutmsg` commands; the Lua master-layout
-- dispatcher namespace isn't fully documented — check hl.dsp.layout.master.*
hl.bind(mainMod .. " + R",         hl.dsp.exec_cmd("hyprctl dispatch layoutmsg orientationnext"))
hl.bind(mainMod .. " + M",         hl.dsp.exec_cmd("hyprctl dispatch layoutmsg swapwithmaster"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("hyprctl dispatch layoutmsg addmaster"))
hl.bind(mainMod .. " + ALT + M",   hl.dsp.exec_cmd("hyprctl dispatch layoutmsg removemaster"))

-- Laptop multimedia keys: volume / mic / brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),       { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),      { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),    { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl (bindl -> also works while screen is locked)
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),        { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),    { locked = true })

-- Screenshots
hl.bind("PRINT",              hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))
hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd("hyprshot -m window --clipboard-only"))
hl.bind(mainMod .. " + SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m output --clipboard-only"))

------------------------------
---- WINDOWS AND WORKSPACES ----
------------------------------

-- Ignore maximize requests from all apps
hl.window_rule({
  name = "suppress-maximize-events",
  match = { class = ".*" },
  suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
  name = "fix-xwayland-drags",
  match = {
    class = "^$",
    title = "^$",
    xwayland = true,
    float = true,
    fullscreen = false,
    pin = false,
  },
  no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
  name = "move-hyprland-run",
  match = { class = "hyprland-run" },
  move = "20 monitor_h-120",
  float = true,
})
